services:
    postgres:
        image: ankane/pgvector:latest
        container_name: ecommerce_postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 12345
            POSTGRES_DB: dev-ecommerce
        ports:
            - "5433:5432"
        volumes:
            - pg_ecommerce_data:/var/lib/postgresql/data
    redis:
        image: redis:7.2
        container_name: redis
        restart: always
        ports:
            - "6379:6379"
volumes:
    pg_ecommerce_data:
